version: "3.8"

services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    env_file:
      - .env
      - .env.secrets
    ports:
      - "5672:5672"
    expose:
      - 5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  fax-transmitter:
    image: ecorrouge/fax-transmitter
    container_name: fax_transmitter
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env.secrets
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./tests/test_volume:/app/test_volume